---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: tempo
spec:
  host: tempo
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tempo
spec:
  gateways:
  - istio-system/frontend-gateway
  - mesh
  hosts:
  - jaeger-collector.skupper.svc.cluster.local
  - jaeger-query-rhsi2.example.com
  http:
  - match:
    - port: 14268
    route:
    - destination:
        host: tempo.openshift-distributed-tracing.svc.cluster.local
        port:
          number: 14268
      weight: 100
  - match:
    - port: 9411
    route:
    - destination:
        host: tempo.openshift-distributed-tracing.svc.cluster.local
        port:
          number: 9411
      weight: 100
  - match:
    - port: 4317
    route:
    - destination:
        host: tempo.openshift-distributed-tracing.svc.cluster.local
        port:
          number: 4317
      weight: 100
  - match:
    - port: 4318
    route:
    - destination:
        host: tempo.openshift-distributed-tracing.svc.cluster.local
        port:
          number: 4318
      weight: 100
  - match:
    - port: 14267
    route:
    - destination:
        host: tempo.openshift-distributed-tracing.svc.cluster.local
        port:
          number: 14267
      weight: 100
  - match:
    - port: 14250
    route:
    - destination:
        host: tempo.openshift-distributed-tracing.svc.cluster.local
        port:
          number: 14250
      weight: 100
  - route:
    - destination:
        host: tempo.openshift-distributed-tracing.svc.cluster.local
        port:
          number: 80
      weight: 100
