{
 "title": "RHSI",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "traceid" }
  ]
 },
 "panels": [
  {
   "title": "RHSI Octets Total",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (address, direction) (rate(octets_total[5m])* 8)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Flows",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by(address, destSite) (rate(flows_total[5m]))",
     "legendFormat": "{{address}}/{{destSite}}"
    }
   ]
  },
  {
   "title": "Active Flows",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum by(address, destSite) (rate(active_flows[5m]))",
     "legendFormat": "{{address}}/{{destSite}}"
    }
   ]
  },
  {
   "title": "Application traces",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance, app) (rate(tracingcalls_total[5m]))",
     "legendFormat": "{{app}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Application responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum by (code, instance, app) (rate(response_total[5m]))",
     "legendFormat": "{{code}} {{app}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Flow latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(flow_latency_microseconds_bucket[5m]))",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Incoming Requests By Source And Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(istio_requests_total[5m])",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    }
   ]
  },
  {
   "title": "trace",
   "type": "traces",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 17 },
   "targets": [
    { "limit": 20, "query": "$traceid", "tableType": "traces" }
   ]
  }
 ]
}