kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: rhsi2
networking:
  apiServerPort: 6443
  apiServerAddress: 127.0.0.1
  podSubnet: "10.252.0.0/16"
  serviceSubnet: "10.34.0.0/16"
nodes:
- role: control-plane
  image: docker.io/kindest/node:v1.26.0
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
    listenAddress: 127.0.0.1
  - containerPort: 30443
    hostPort: 443
    listenAddress: 127.0.0.1
  - containerPort: 32601
    hostPort: 32601
    listenAddress: 127.0.0.1
  - containerPort: 32602
    hostPort: 32602
    listenAddress: 127.0.0.1
  - containerPort: 32603
    hostPort: 32603
    listenAddress: 127.0.0.1
  - containerPort: 32604
    hostPort: 32604
    listenAddress: 127.0.0.1
  extraMounts:
  - hostPath: /root/.docker/config.json
    containerPath: /var/lib/kubelet/config.json
- role: worker
  image: docker.io/kindest/node:v1.26.0
  extraMounts:
  - hostPath: /root/.docker/config.json
    containerPath: /var/lib/kubelet/config.json
