apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se-sso
  namespace: mockbin
spec:
  hosts:
  - sso.example.com
  ports:
  - name: https
    number: 443
    protocol: HTTPS
    targetPort: 443
  resolution: DNS
