apiVersion: v1
data:
  console: "true"
  console-authentication: internal
  console-password: changeme
  console-user: admin
  ingress: nodeport
  ingress-host: rhsi1.example.com
  flow-collector: "true"
  name: rhsi1
  router-console: "false"
  router-logging: ""
  router-mode: interior
  service-controller: "true"
  service-sync: "true"
kind: ConfigMap
metadata:
  name: skupper-site
