apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-minio
spec:
  gateways:
  - istio-system/frontend-gateway
  hosts:
  - minio.openshift-distributed-tracing.svc.cluster.local
  http:
  - match:
    - headers:
        User-Agent:
          prefix: Mozilla
    route:
    - destination:
        host: minio
        port:
          number: 9001
        subset: v1
      weight: 100
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: minio
        port:
          number: 9000
        subset: v1
      weight: 100
