apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tempo
  name: tempo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: tempo
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tempo
        version: v1
    spec:
      containers:
      - command:
        - /tempo
        - -config.file=/etc/tempo.yaml
        image: grafana/tempo:latest
        imagePullPolicy: IfNotPresent
        name: tempo
        ports:
        - containerPort: 9411
          name: zipkin-9411
          protocol: TCP
        - containerPort: 14250
          name: tls-grpc-jaeger
          protocol: TCP
        - containerPort: 14267
          name: http-c-t-trft
          protocol: TCP
        - containerPort: 14268
          name: http-c-b-trft
          protocol: TCP
        - containerPort: 4317
          name: grpc-otlp
          protocol: TCP
        - containerPort: 4318
          name: http-otlp
          protocol: TCP
        - containerPort: 3200
          name: tempo-http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tempo.yaml
          name: config
          subPath: tempo.yaml
        - mountPath: /data
          name: data
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: tempo-config
        name: config
      - name: data
        persistentVolumeClaim:
          claimName: tempo-data
