apiVersion: v1
kind: Service
metadata:
  labels:
    app: tempo
    version: v1
  name: tempo
spec:
  ports:
  - name: http-query
    port: 80
    protocol: TCP
    targetPort: 3200
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: http-otlp
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: http-c-tchan-trft
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: http-c-binary-trft
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: tls-grpc-jaeger
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: http-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: tempo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
