# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 120s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 10s # is set to the global default (10s).
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "mockbin"
    scheme: http
    metrics_path: "/stats/prometheus"
    static_configs:
      - targets: ["rhsi1-mockbin.skupper.svc.cluster.local:15020","rhsi2-mockbin.skupper.svc.cluster.local:15020"]
  - job_name: "skupper"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    metrics_path: "/api/v1alpha1/metrics"
    static_configs:
      - targets: ["rhsi1-metrics.skupper.svc.cluster.local:8010","rhsi2-metrics.skupper.svc.cluster.local:8010"]
  - job_name: kubernetes-service-endpoints
    kubernetes_sd_configs:
    - namespaces:
        names:
        - mockbin
        - skupper
        - openshift-distributed-tracing
        - istio-system
      role: endpoints
    relabel_configs:
    - action: keep
      regex: true
      source_labels:
      - __meta_kubernetes_service_annotation_prometheus_io_scrape
    - action: replace
      regex: (https?)
      source_labels:
      - __meta_kubernetes_service_annotation_prometheus_io_scheme
      target_label: __scheme__
    - action: replace
      regex: (.+)
      source_labels:
      - __meta_kubernetes_service_annotation_prometheus_io_path
      target_label: __metrics_path__
    - action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      source_labels:
      - __address__
      - __meta_kubernetes_service_annotation_prometheus_io_port
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)
    - action: replace
      source_labels:
      - __meta_kubernetes_namespace
      target_label: kubernetes_namespace
    - action: replace
      source_labels:
      - __meta_kubernetes_service_name
      target_label: kubernetes_name
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_node_name
      target_label: kubernetes_node
    - action: drop
      regex: prometheus;3001
      source_labels:
      - __meta_kubernetes_service_name
      - __meta_kubernetes_pod_container_port_number
  - job_name: kubernetes-service-endpoints-slow
    kubernetes_sd_configs:
    - namespaces:
        names:
        - mockbin
        - skupper
        - openshift-distributed-tracing
        - istio-system
      role: endpoints
    relabel_configs:
    - action: keep
      regex: true
      source_labels:
      - __meta_kubernetes_service_annotation_prometheus_io_scrape_slow
    - action: replace
      regex: (https?)
      source_labels:
      - __meta_kubernetes_service_annotation_prometheus_io_scheme
      target_label: __scheme__
    - action: replace
      regex: (.+)
      source_labels:
      - __meta_kubernetes_service_annotation_prometheus_io_path
      target_label: __metrics_path__
    - action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      source_labels:
      - __address__
      - __meta_kubernetes_service_annotation_prometheus_io_port
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)
    - action: replace
      source_labels:
      - __meta_kubernetes_namespace
      target_label: kubernetes_namespace
    - action: replace
      source_labels:
      - __meta_kubernetes_service_name
      target_label: kubernetes_name
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_node_name
      target_label: kubernetes_node
    - action: drop
      regex: prometheus;3001
      source_labels:
      - __meta_kubernetes_service_name
      - __meta_kubernetes_pod_container_port_number
    scrape_interval: 5m
    scrape_timeout: 30s
  - honor_labels: true
    job_name: prometheus-pushgateway
    kubernetes_sd_configs:
    - namespaces:
        names:
        - mockbin
        - skupper
        - openshift-distributed-tracing
      role: service
    relabel_configs:
    - action: keep
      regex: pushgateway
      source_labels:
      - __meta_kubernetes_service_annotation_prometheus_io_probe
  - job_name: kubernetes-services
    kubernetes_sd_configs:
    - namespaces:
        names:
        - mockbin
        - skupper
        - openshift-distributed-tracing
        - istio-system
      role: service
    metrics_path: /probe
    params:
      module:
      - http_2xx
    relabel_configs:
    - action: keep
      regex: true
      source_labels:
      - __meta_kubernetes_service_annotation_prometheus_io_probe
    - source_labels:
      - __address__
      target_label: __param_target
    - replacement: blackbox
      target_label: __address__
    - source_labels:
      - __param_target
      target_label: instance
    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)
    - source_labels:
      - __meta_kubernetes_namespace
      target_label: kubernetes_namespace
    - source_labels:
      - __meta_kubernetes_service_name
      target_label: kubernetes_name
  - job_name: kubernetes-pods
    kubernetes_sd_configs:
    - namespaces:
        names:
        - mockbin
        - skupper
        - openshift-distributed-tracing
        - istio-system
      role: pod
    relabel_configs:
    - action: keep
      regex: true
      source_labels:
      - __meta_kubernetes_pod_annotation_prometheus_io_scrape
    - action: replace
      regex: (.+)
      source_labels:
      - __meta_kubernetes_pod_annotation_prometheus_io_path
      target_label: __metrics_path__
    - action: replace
      regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
      replacement: '[$2]:$1'
      source_labels:
      - __meta_kubernetes_pod_annotation_prometheus_io_port
      - __meta_kubernetes_pod_ip
      target_label: __address__
    - action: replace
      regex: (\d+);((([0-9]+?)(\.|$)){4})
      replacement: $2:$1
      source_labels:
      - __meta_kubernetes_pod_annotation_prometheus_io_port
      - __meta_kubernetes_pod_ip
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - action: replace
      source_labels:
      - __meta_kubernetes_namespace
      target_label: kubernetes_namespace
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_name
      target_label: kubernetes_pod_name
    - action: drop
      regex: Pending|Succeeded|Failed
      source_labels:
      - __meta_kubernetes_pod_phase
  - job_name: kubernetes-pods-slow
    kubernetes_sd_configs:
    - namespaces:
        names:
        - mockbin
        - skupper
        - openshift-distributed-tracing
        - istio-system
      role: pod
    relabel_configs:
    - action: keep
      regex: true
      source_labels:
      - __meta_kubernetes_pod_annotation_prometheus_io_scrape_slow
    - action: replace
      regex: (.+)
      source_labels:
      - __meta_kubernetes_pod_annotation_prometheus_io_path
      target_label: __metrics_path__
    - action: replace
      regex: (\d+);(([A-Fa-f0-9]{1,4}::?){1,7}[A-Fa-f0-9]{1,4})
      replacement: '[$2]:$1'
      source_labels:
      - __meta_kubernetes_pod_annotation_prometheus_io_port
      - __meta_kubernetes_pod_ip
      target_label: __address__
    - action: replace
      regex: (\d+);((([0-9]+?)(\.|$)){4})
      replacement: $2:$1
      source_labels:
      - __meta_kubernetes_pod_annotation_prometheus_io_port
      - __meta_kubernetes_pod_ip
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - action: replace
      source_labels:
      - __meta_kubernetes_namespace
      target_label: kubernetes_namespace
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_name
      target_label: kubernetes_pod_name
    - action: drop
      regex: Pending|Succeeded|Failed
      source_labels:
      - __meta_kubernetes_pod_phase
    scrape_interval: 5m
    scrape_timeout: 30s
