apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cilium/global-service: "true"
  labels:
    app: prometheus
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
  name: prometheus
spec:
  ports:
  - name: http-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    deployment: prometheus
  type: ClusterIP
