apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mockbin
spec:
  gateways:
  - istio-system/frontend-gateway
  - mesh
  hosts:
  - rhsi2.example.com
  - rhsi2-mockbin.skupper.svc.cluster.local
  http:
  - route:
    - destination:
        host: mockbin
        port:
          number: 8080
      weight: 100
  tls:
  - match:
    - port: 443
      sniHosts:
      - rhsi2.example.com
    route:
    - destination:
        host: mockbin
        port:
          number: 8080
      weight: 100
