apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mockbin
spec:
  gateways:
  - istio-system/frontend-gateway
  hosts:
  - rhsi1.example.com
  - rhsi1-mockbin.skupper.cluster.local
  http:
  - match:
    - port: 8080
    route:
    - destination:
        host: mockbin
        port:
          number: 8080
      weight: 100
  - match:
    - port: 15020
    route:
    - destination:
        host: mockbin
        port:
          number: 15020
      weight: 100
  tls:
  - match:
    - port: 443
      sniHosts:
      - rhsi1.example.com
    route:
    - destination:
        host: mockbin
