---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: se-rhsi2-external
spec:
  hosts:
  - rhsi2.example.com
  ports:
  - name: https
    number: 443
    protocol: HTTPS
    targetPort: 443
  resolution: DNS
