apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mockbin
  namespace: mockbin
spec:
  host: mockbin
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 15020
        tls:
          mode: DISABLE
