apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: rhsi2-mockbin-skupper
  namespace: mockbin
spec:
  hosts:
  - rhsi2-mockbin.skupper.svc.cluster.local
  ports:
  - name: http
    number: 8080
    protocol: HTTP
    targetPort: 8080
  - name: http-metrics
    number: 15020
    protocol: HTTP
    targetPort: 15020
  resolution: DNS
---

