apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: rhsi2
  namespace: metallb-system
spec:
  addresses:
  - 192.168.192.55-192.168.192.55
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system

