apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: rhsi1
  namespace: metallb-system
spec:
  addresses:
  - 192.168.192.54-192.168.192.54
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system

