apiVersion: v1
data:
  client.json: ewoJIndlYiI6IHsKCQkidG9rZW5faW50cm9zcGVjdGlvbl91cmkiOiAiaHR0cHM6Ly9zc28uZXhhbXBsZS5jb20vcmVhbG1zL0V4YW1wbGUvcHJvdG9jb2wvb3BlbmlkLWNvbm5lY3QvdG9rZW4vaW50cm9zcGVjdCIsCgkJImNsaWVudF9pZCI6ICJFeGFtcGxlIiwKCQkiY2xpZW50X3NlY3JldCI6ICIuLi4uIiwKCQkid2VsbC1rbm93biI6ICJodHRwczovL3Nzby5leGFtcGxlLmNvbS9yZWFsbXMvRXhhbXBsZS8ud2VsbC1rbm93bi9vcGVuaWQtY29uZmlndXJhdGlvbiIsCgkJImlzc3VlciI6ICJodHRwczovL3Nzby5leGFtcGxlLmNvbS9yZWFsbXMvRXhhbXBsZSIKCX0sCgkidG9rZW4iOiB7CgkJInVzZXJuYW1lIjogInVzZXJuYW1lIiwKCQkiZ3JvdXAiOiAiZ3JvdXAiCgl9Cn0K
kind: Secret
metadata:
  creationTimestamp: null
  name: mockbin-oidc
