apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
    app.kubernetes.io/component: minio
    app.kubernetes.io/instance: minio
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: minio
  name: minio
spec:
  ports:
  - name: tcp-9000
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: tcp-9001
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: minio
    deployment: minio
    version: v1
  sessionAffinity: None
  type: ClusterIP
